name: C++ Autograding

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Compile and Test
      run: |
        chmod +x scripts/evaluate.sh
        ./scripts/evaluate.sh
